---
- name: Install packages
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - autoconf
      - automake
      - bzip2
      - dpkg-dev
      - file
      - g++
      - gcc
      - gdb
      - imagemagick
      - libbz2-dev
      - libc6-dev
      - libcurl4-openssl-dev
      - libdb-dev
      - libevent-dev
      - libffi-dev
      - libgdbm-dev
      - libgeoip-dev
      - libglib2.0-dev
      - libgmp-dev
      - libjpeg-dev
      - libkrb5-dev
      - liblzma-dev
      - libmagickcore-dev
      - libmagickwand-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libpng-dev
      - libpq-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libtool-bin
      - libwebp-dev
      - libxml2-dev
      - libxslt-dev
      - libyaml-dev
      - make
      - openssh-client
      - patch
      - procps
      - unzip
      - xz-utils
      - zlib1g-dev
      - libmysqlclient-dev
  tags:
    - devtools

- name: Enable ptrace
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/10-ptrace.conf
    regexp: '^(kernel.yama.ptrace_scope)\s+=\s+\d+'
    line: '\1 = 0'
    backrefs: true
  tags:
    - devtools
