---
- name: Install delta
  ansible.builtin.shell: |
    set -o pipefail
    mise use --global --yes delta
  args:
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0
  tags:
    - delta
