---

- name: create temporary directory
  tempfile:
    state: directory
  register: temp
  when:
    ansible_architecture == "x86_64"
  tags:
    - ghq

- name: download
  unarchive:
    src: "https://github.com/x-motemen/ghq/releases/download/v{{ ghq_version }}/ghq_linux_amd64.zip"
    dest: "{{ temp.path }}"
    remote_src: yes
  when:
    ansible_architecture == "x86_64"
  tags:
    - ghq

- name: copy
  become: yes
  copy:
    src: "{{ temp.path }}/ghq_linux_amd64/ghq"
    dest: /usr/local/bin
    mode: +x
    remote_src: yes
  when:
    ansible_architecture == "x86_64"
  tags:
    - ghq

- name: remove temporary directory
  file:
    path: "{{ temp.path }}"
    state: absent
  when:
    ansible_architecture == "x86_64"
  tags:
    - ghq
