---
- name: Install ghq
  ansible.builtin.shell: |
    set -o pipefail
    mise use --global --yes ghq
  args:
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0
  tags:
    - ghq
