---

- name: create temporary directory
  tempfile:
    state: directory
  register: temp
  tags:
    - caddy

- name: "[arm64] download"
  unarchive:
    src: "https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_arm64.tar.gz"
    dest: "{{ temp.path }}"
    remote_src: yes
  when:
    ansible_architecture == "aarch64"
  tags:
    - caddy

- name: "[amd64] download"
  unarchive:
    src: "https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_amd64.tar.gz"
    dest: "{{ temp.path }}"
    remote_src: yes
  when:
    ansible_architecture == "x86_64"
  tags:
    - caddy

- name: copy
  become: yes
  copy:
    src: "{{ temp.path }}/caddy"
    dest: /usr/local/bin
    mode: +x
    remote_src: yes
  tags:
    - caddy

- name: remove temporary directory
  file:
    path: "{{ temp.path }}"
    state: absent
  tags:
    - caddy
