---
- name: Install mise
  ansible.builtin.shell: |
    set -o pipefail
    curl https://mise.jdx.dev/install.sh | bash
  args:
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0
  tags:
    - mise
