---
- name: Install cmake
  ansible.builtin.shell: |
    set -o pipefail
    mise use --global cmake
  args:
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0
  tags:
    - cmake
