---
- name: Clone repository  # noqa: latest[git]
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1
  tags:
    - fzf

- name: Install fzf
  ansible.builtin.command: ~/.fzf/install --all
  register: result
  changed_when: result.rc == 0
  tags:
    - fzf
