---
- name: Install packages
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - git
      - openssh-client
      - procps
  tags:
    - scm

- name: Install gitignore.io command
  ansible.builtin.command: git config --global alias.ignore '!gi() { curl -sL https://www.toptal.com/developers/gitignore/api/$@ ;}; gi'
  register: result
  changed_when: result.rc == 0
  tags:
    - scm
