---
- name: Install packages
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - git
      - openssh-client
      - procps
  tags:
    - scm

- name: Set gitignore.io alias in git config
  community.general.git_config:
    name: alias.ignore
    scope: global
    value: "!gi() { curl -sL https://www.toptal.com/developers/gitignore/api/$@ ;}; gi"
  tags:
    - scm
