---
  - name: Install go
    ansible.builtin.shell: |
      set -o pipefail
      mise use --global --yes go
    args:
      executable: /bin/bash
    register: result
    changed_when: result.rc == 0
    tags:
      - go
