---
- name: Install node
  ansible.builtin.shell: |
    set -o pipefail
    mise use --global node
  args:
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0
  tags:
    - node
