---
- name: Install lsd
  ansible.builtin.shell: |
    set -o pipefail
    mise use --global --yes lsd
  args:
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0
  tags:
    - lsd
