---

- name: add apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  tags:
    - docker

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - docker

- name: add user to docker group
  become: yes
  shell: usermod -aG docker "{{ ansible_user_id }}"
  tags:
    - docker

- name: start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker

- name: download docker-compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
  tags:
    - docker
